import "./globals.css";
import ReduxProvider from "./ReduxProvider";

export const metadata = {
  title: "Team Shiksha",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased">
        {/* ReduxProvider is client component */}
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  );
}
